config/routes.rb
Rails.application.routes.draw do
  resources :stories
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]

  root 'stories#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/story.rb
class Story < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :stories
    
    validates :email, uniqueness: true, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by_email(params[:user][:email])
    if @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to :root
    else
      render :new, notice: 'Usuario o clave incorrecto'
    end
  end

  def destroy
    reset_session
    redirect_to root_path
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]

  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(story_params)
    @story.user = helpers.current_user
    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url, notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit(:title, :picture, :content, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to root_path
      else
        render :new, notice: "No ha sido posible crear el usuario."
      end
  end

  def show
    @user = User.includes(:stories).find(helpers.current_user.id)
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def logged?
        session[:user_id].present?
    end

    def current_user
        User.find(session[:user_id])
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pictory</title>
    <%= csrf_meta_tags %>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/sandstone/bootstrap.min.css" rel="stylesheet" integrity="sha384-G3G7OsJCbOk1USkOY4RfeX1z27YaWrZ1YuaQ5tbuawed9IoreRDpWpTkZLXQfPm3" crossorigin="anonymous">
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <% if notice %>
        <div class="alert alert-dismissible alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <h4>Información</h4>
          <p><%= notice %></p>
        </div>
      <% end %>
      <% if alert %>
        <div class="alert alert-dismissible alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <h4>Atención</h4>
          <p><%= alert %></p>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">PicStory</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% unless logged? %>
        <li><%=link_to 'Registro', new_user_path unless logged? %></li>
        <li><%=link_to 'Iniciar Sesión', new_session_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <!-- ¡Pending implementation! Should work toggling between sign_in and sign_out -->
        <% if logged? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-user-circle-o" style="font-size:24px""></i>
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%=link_to 'Create PicStory', new_story_path %></li>
            <li><%=link_to 'My PicStories', user_path(current_user) %></a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Sign Out', session_path(current_user), method: :delete %><a href="#"></a></li>
          </ul>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/stories/_form.html.erb
<%= form_with(model: story, local: true) do |form| %>
  <% if story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(story.errors.count, "error") %> no permitieron que se registro la historia:</h2>

      <ul>
      <% story.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :story_title %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.text_field :picture, id: :story_picture %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :story_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing PicStory</h1>

<%= render 'form', story: @story %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<div class="row">
  <div class="col-xs-8 col-sm-10 col-md-10">
    <h1>PicStories</h1>
  </div>
</div>

<div class="row">
  <% @stories.reverse.each do |story| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <%= link_to(image_tag(story.picture), story) if story.picture? %>
        <div class="caption">
          <h3><%= story.title %></h3>
          <small><%= time_ago_in_words(story.created_at) %> ago</small>
          <p><%= story.content.truncate(150)  %></p>
          <p><%= link_to 'Show', story, class: "btn btn-primary" %> 
          <%= link_to 'Edit', edit_story_path(story), class: "btn btn-warning" %> 
          <%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>


<br>

app/views/stories/new.html.erb
<h1>New PicStory</h1>

<%= render 'form', story: @story %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<div class="container">

      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
          <%= image_tag(@story.picture, style: "max-width: 100%; border-radius: 10px;") if @story.picture? %>
        </div>
        <div class="col-md-2"></div>
      </div>
      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
          <h1><%= @story.title %></h1>
          <small><%= time_ago_in_words(@story.created_at) %> ago</small>
        </div>
        <div class="col-md-2"></div>
      </div>

      <hr>
      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
          <p><%= @story.content %></p>
        </div>
        <div class="col-md-2"></div>
      </div>
      <br>
      <div class="row">
        <div class="col-md-8"></div>
        <div class="col-md-2">
          <p><%= link_to 'Edit', edit_story_path(@story), class: "btn btn-warning btn-sm" %> <%= link_to 'Back', stories_path, class: "btn btn-info btn-sm" %></p>
        </div>
        <div class="col-md-2"></div>
      </div>

</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<div class="row">
<div class="col-md-3">
<h1>Registro de usuario</h1>
<%= form_with(model: @user, local: true) do |form| %>
 <% if @user.errors.any? %>
   <div id="error_explanation">
     <h2><%= pluralize(@user.errors.count, "error") %> no permite que se registre el usuario:</h2>

     <ul>
     <% @user.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
     </ul>
   </div>
 <% end %>
 <div class="form-group">
   <%= form.label :Nombre  %>
   <%= form.text_field :name, id: :user_name, class:'form-control' %>
 </div>

 <div class="form-group">
   <%= form.label :email %>
   <%= form.email_field :email, id: :user_email, class:'form-control' %>
 </div>

 <div class="form-group">
   <%= form.label :password %>
   <%= form.password_field :password, id: :user_password, class:'form-control' %>
 </div>
<div class="form-group">
   <%= form.label :password_confirmation %>
   <%= form.password_field :password_confirmation, id: :user_password_confirmation , class:'form-control'%>
 </div>
 <div class="form-group">
   <%= form.submit class:'btn btn-success' %>
 </div>
<% end %>


</div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-xs-8 col-sm-10 col-md-10">
    <h1>PicStories</h1>
  </div>
  <div class="col-xs-4 col-sm-2 col-md-2">
    <%= link_to 'New story', new_story_path, class: "btn btn-info btn-sm" %>
  </div>
</div>

<div class="row">
  <% @user.stories.reverse.each do |story| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <%= link_to(image_tag(story.picture), story) if story.picture? %>
        <div class="caption">
          <h3><%= story.title %></h3>
          <small><%= time_ago_in_words(story.created_at) %> ago</small>
          <p><%= story.content.truncate(150)  %></p>
          <p><%= link_to 'Show', story, class: "btn btn-primary" %> <%= link_to 'Edit', edit_story_path(story), class: "btn btn-warning" %> <%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>